spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${su.db.host:101.34.215.91}:${su.db.port:3306}/${su.db.database}?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: ${su.db.psw:rootroot}
  redis:
    host: 127.0.0.1       # Redis服务器地址
    database: 1           # Redis数据库索引（默认为0）
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 1000ms       # 连接超时时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8