server:
  port: 8201
spring:
  application:
    name: data-analysis
  profiles:
    active: '@profileActive@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

feign:
  okhttp:
    enabled: true
