server:
  port: 8201
spring:
  application:
    name: data-analysis
  profiles:
    active: '@profileActive@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  name-server: '101.34.215.91:9876'
  consumer:
    group: sus_group
  producer:
    group: sus_group
    send-message-timeout: 5000

feign:
  okhttp:
    enabled: true
